name: ci
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r vllmbench/requirements-dev.txt
      - run: ruff check vllmbench/src vllmbench/tests
      - run: black --check vllmbench/src vllmbench/tests
      - run: isort --check-only vllmbench/src vllmbench/tests

  typecheck:
    name: typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r vllmbench/requirements-dev.txt
      - run: mypy --ignore-missing-imports vllmbench/src

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r vllmbench/requirements-dev.txt
      - run: pytest -q
